//! Seed the global config tier with in-tree defaults on launch.
//!
//! Each entry in [`DEFAULT_PERSONAS`] / [`DEFAULT_PRINCIPLES`] is
//! written into `<global>/<dir>/<name>.toml` if absent. User edits
//! to an existing file are preserved (we never overwrite). Deletions
//! are NOT remembered — a deleted default reappears on next launch.
//! If we want delete-stickiness later, the plan is a marker file
//! plus a "Restore defaults" action in settings.

use std::io;
use std::path::Path;
use tracing::info;

// `DEFAULT_PERSONAS` and `DEFAULT_PRINCIPLES` are generated by
// `build.rs` from `<repo>/personas/*.toml` and
// `<repo>/principles/*.toml`. Source of truth is the on-disk files;
// new files are picked up automatically on the next build.
//
// Default principles get seeded into `<global>/principles/` and
// picked up by the principled workflow's `Principle::list` via the
// same `Resolver` the personas loader uses, so a fresh install ships
// with the full software-principles library — every installed
// principle is always active for its declared `applies_to` tools.
// Editing the seeded copy is the supported way to tune them.
include!(concat!(env!("OUT_DIR"), "/seed_defaults.rs"));


pub fn seed(global_config_dir: &Path) -> io::Result<()> {
    let personas_dir = global_config_dir.join("personas");
    for (name, body) in DEFAULT_PERSONAS {
        let path = personas_dir.join(format!("{name}.toml"));
        if path.exists() {
            continue;
        }
        info!(path = %path.display(), "seeding default persona");
        std::fs::create_dir_all(&personas_dir)?;
        std::fs::write(&path, body)?;
    }

    let principles_dir = global_config_dir.join("principles");
    for (name, body) in DEFAULT_PRINCIPLES {
        let path = principles_dir.join(format!("{name}.toml"));
        if path.exists() {
            continue;
        }
        info!(path = %path.display(), "seeding default principle");
        std::fs::create_dir_all(&principles_dir)?;
        std::fs::write(&path, body)?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn seed_creates_all_defaults() {
        let tmp = tempdir().unwrap();
        seed(tmp.path()).unwrap();
        for (name, _) in DEFAULT_PERSONAS {
            assert!(
                tmp.path().join(format!("personas/{name}.toml")).is_file(),
                "missing seeded persona: {name}"
            );
        }
        for (name, _) in DEFAULT_PRINCIPLES {
            assert!(
                tmp.path().join(format!("principles/{name}.toml")).is_file(),
                "missing seeded principle: {name}"
            );
        }
    }

    #[test]
    fn second_seed_preserves_user_persona() {
        let tmp = tempdir().unwrap();
        seed(tmp.path()).unwrap();
        let path = tmp.path().join("personas/assistant.toml");
        std::fs::write(&path, b"user content").unwrap();
        seed(tmp.path()).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "user content");
    }

    #[test]
    fn second_seed_resurrects_deleted_default() {
        let tmp = tempdir().unwrap();
        seed(tmp.path()).unwrap();
        let path = tmp.path().join("personas/researcher.toml");
        std::fs::remove_file(&path).unwrap();
        seed(tmp.path()).unwrap();
        assert!(path.is_file());
    }
}
